// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8s_QJnJXqXrpRwT_3poqmZawots31EE8',
    appId: '1:127725032217:web:01bf4b1e1ccb7d88f86b88',
    messagingSenderId: '127725032217',
    projectId: 'flutter-course-wael-53e16',
    authDomain: 'flutter-course-wael-53e16.firebaseapp.com',
    storageBucket: 'flutter-course-wael-53e16.firebasestorage.app',
    measurementId: 'G-QCZBE3TWBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5d9AKhvhgMdlUznL7IouIQ1_RR7djm6Q',
    appId: '1:127725032217:android:35ea46e5b586a8c1f86b88',
    messagingSenderId: '127725032217',
    projectId: 'flutter-course-wael-53e16',
    storageBucket: 'flutter-course-wael-53e16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzLkDEiWzqDSD0B5EkIeK4g3v4JAtDfew',
    appId: '1:127725032217:ios:a7f61ca5f3f9ad18f86b88',
    messagingSenderId: '127725032217',
    projectId: 'flutter-course-wael-53e16',
    storageBucket: 'flutter-course-wael-53e16.firebasestorage.app',
    iosBundleId: 'com.example.flutterCourseWael',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzLkDEiWzqDSD0B5EkIeK4g3v4JAtDfew',
    appId: '1:127725032217:ios:a7f61ca5f3f9ad18f86b88',
    messagingSenderId: '127725032217',
    projectId: 'flutter-course-wael-53e16',
    storageBucket: 'flutter-course-wael-53e16.firebasestorage.app',
    iosBundleId: 'com.example.flutterCourseWael',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8s_QJnJXqXrpRwT_3poqmZawots31EE8',
    appId: '1:127725032217:web:ee600c2f95216b81f86b88',
    messagingSenderId: '127725032217',
    projectId: 'flutter-course-wael-53e16',
    authDomain: 'flutter-course-wael-53e16.firebaseapp.com',
    storageBucket: 'flutter-course-wael-53e16.firebasestorage.app',
    measurementId: 'G-6BYK7MJDBG',
  );
}
